apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops
  template:
    metadata:
      labels:
        app: mlops
    spec:
      containers:
      - name: mlops-container
        image: sakshatshende/mlops-demo:v1
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  type: LoadBalancer
  selector:
    app: mlops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
